package:
    name: repo
    version: 0.0.1

source:
    git_rev: 
    git_url: https://github.com/necla-ml/repo.git

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - make

build:
    preserve_egg_dir: False
    entry_points:
        - repo = repo.__main__:cli

test:
    imports:
        -

about:
    home: https://github.com/necla-ml/repo
